INPUT_TEXT: "text_field"
INPUT_PASSWORD: "password"
INPUT_CHECHBOX: "checkbox"
INPUT_RADIO: "radio"
INPUT_SELECT: "select"
INPUT_TEXTAREA: "textarea"
INPUT_DATE: "datepicture"

#INPUT_RESET: "reset"
#INPUT_HIDDEN: "hidden"
#INPUT_FILE: "file"
#INPUT_BUTTON: "button"
#INPUT_IMAGE: "image"
#INPUT_SUBMIT: "submit"
#INPUT_IMAGE: "image"