INPUT_TEXT: "text_field"
INPUT_PASSWORD: "password"
INPUT_CHECHBOX: "checkbox"
INPUT_RADIO: "radio"
INPUT_SELECT: "select"
INPUT_TEXTAREA: "textarea"
INPUT_DATE: "datepicture"
PAYMENT: [{name: "Ordinario", type: "1"},
          {name: "Extra", type: "1.5"},
          {name: "Doble", type: "2"}]