development:
  INPUT_TEXT: "text_field"
  INPUT_PASSWORD: "password"
  INPUT_CHECHBOX: "checkbox"
  INPUT_RADIO: "radio"
  INPUT_SELECT: "select"
  INPUT_TEXTAREA: "textarea"
  INPUT_DATE: "datepicture"
  VALIDATION_TIME: "5"
  REPORTS: {
    PAYMENT_PROOF: "1",
  	GENERAL_PAYROLL: "2",
  	PAYMENT_TYPE_REPORT: "3",
    ACCRUED_WAGES_DATES: "4"
  }
  FIREBIRD: [
    { ITDSOP: 13,
  	ITDSOP2: 320,
  	IUSUARIOULT: "RRHH",
  	IUSUARIO: "RRHH",
  	ICUENTA: 21010210 }
  ]

test:
  INPUT_TEXT: "text_field"
  INPUT_PASSWORD: "password"
  INPUT_CHECHBOX: "checkbox"
  INPUT_RADIO: "radio"
  INPUT_SELECT: "select"
  INPUT_TEXTAREA: "textarea"
  INPUT_DATE: "datepicture"
  VALIDATION_TIME: "5"
  REPORTS: {
    PAYMENT_PROOF: "1",
  	GENERAL_PAYROLL: "2",
  	PAYMENT_TYPE_REPORT: "3",
    ACCRUED_WAGES_DATES: "4"
  }
  FIREBIRD: [
    { ITDSOP: 13,
  	ITDSOP2: 320,
  	IUSUARIOULT: "RRHH",
  	IUSUARIO: "RRHH",
  	ICUENTA: 21010210 }
  ]


production:
  INPUT_TEXT: "text_field"
  INPUT_PASSWORD: "password"
  INPUT_CHECHBOX: "checkbox"
  INPUT_RADIO: "radio"
  INPUT_SELECT: "select"
  INPUT_TEXTAREA: "textarea"
  INPUT_DATE: "datepicture"
  VALIDATION_TIME: "5"
  REPORTS: {
    PAYMENT_PROOF: "1",
  	GENERAL_PAYROLL: "2",
  	PAYMENT_TYPE_REPORT: "3",
    ACCRUED_WAGES_DATES: "4"
  }
  FIREBIRD: [
    { ITDSOP: 13,
  	ITDSOP2: 320,
  	IUSUARIOULT: "RRHH",
  	IUSUARIO: "RRHH",
  	ICUENTA: 21010210 }
  ]
